export const PRODUCTS = [
  { id:"hoodie", name:"Logo Hoodie", emoji:"👕", category:"Custom Apparel",
    description:"Cozy + photo-ready. Perfect for custom logos.", price:49,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" },
  { id:"collar", name:"Personalized Collar + Tag", emoji:"🏷️", category:"Collars and Tags",
    description:"Name + number. Easy bestseller.", price:24,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" },
  { id:"toy", name:"Squeaky Toy Pack", emoji:"🧸", category:"Toys",
    description:"Bundle packs increase cart value fast.", price:19,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" },
  { id:"harness", name:"Leash + Harness Set", emoji:"🦮", category:"Leashes and Harnesses",
    description:"Matching set. Looks premium in pics.", price:39,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" },
  { id:"bed", name:"Cloud Bed", emoji:"🛏️", category:"Blankets and Beds",
    description:"Comfy, giftable, and always in demand.", price:79,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" },
  { id:"booties", name:"Outdoor Booties", emoji:"🥾", category:"Outerwear and Shoes",
    description:"Winter-ready style + protection.", price:29,
    image:"assets/hero-malinois.png",
    squareLink:"PASTE_SQUARE_PAYMENT_LINK_HERE", storeLink:"PASTE_STORE_VIEW_LINK_HERE" }
];
